"""empty message

Revision ID: 46414d85629b
Revises: add25673684b
Create Date: 2023-04-25 07:16:53.163817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46414d85629b'
down_revision = 'add25673684b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'priority')
    # ### end Alembic commands ###
