"""empty message

Revision ID: 48edaf71b1c0
Revises: fbb243905463
Create Date: 2023-04-11 07:11:26.643501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48edaf71b1c0'
down_revision = 'fbb243905463'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pars_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_pars', sa.Integer(), nullable=True),
    sa.Column('created_ad', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pars_config')
    # ### end Alembic commands ###
