"""empty message

Revision ID: 5d0326384ce6
Revises: fe71d4e9f44c
Create Date: 2023-04-28 20:30:29.533062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d0326384ce6'
down_revision = 'fe71d4e9f44c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
