"""empty message

Revision ID: 72da2f6855de
Revises: eefb29c6ec46
Create Date: 2023-04-30 07:27:52.983755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72da2f6855de'
down_revision = 'eefb29c6ec46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('module', sa.String(length=255), nullable=False),
    sa.Column('component', sa.String(length=255), nullable=True),
    sa.Column('page', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('sub_title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('keywords', sa.String(length=255), nullable=True),
    sa.Column('canonical_full_url', sa.String(length=255), nullable=False),
    sa.Column('user_role_id', sa.Integer(), nullable=True),
    sa.Column('user_auth', sa.Boolean(), nullable=True),
    sa.Column('robots', sa.Boolean(), nullable=True),
    sa.Column('name_menu', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nodes')
    # ### end Alembic commands ###
