"""empty message

Revision ID: e6eed0f16018
Revises: 48edaf71b1c0
Create Date: 2023-04-20 09:43:04.598443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6eed0f16018'
down_revision = '48edaf71b1c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'price')
    # ### end Alembic commands ###
