"""empty message

Revision ID: eefb29c6ec46
Revises: 5d0326384ce6
Create Date: 2023-04-30 07:20:06.037631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eefb29c6ec46'
down_revision = '5d0326384ce6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
